// Scaffolder: builds character entries from CharInfo(Dropped).json and the
// illustration folders under public/brown-dust-2-asset/ui/illust.
//
// Usage: node scripts/generate-roster.mjs
//
// data/characters.ts is the hand-edited SOURCE OF TRUTH — this script never
// touches it. It writes scripts/roster-scaffold.preview.ts instead; when fresh
// game data adds characters, copy the new entries from the preview into
// roster.ts by hand.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// Characters already hand-tuned in data/characters.ts (full costume/skill
// literals) — keep this list in sync when you promote a character, so the
// preview only contains entries worth copying.
const HAND_TUNED_CHAR_IDS = new Set([
  '0001', // Lathel
  '0002', // Justia
  '0003', // Scheherazade
  '0007', // Eclipse
  '0010', // Sylvia
  '0011', // Teresse
  '0012', // Liatris
  '0024', // Diana
  '0610', // Helena
  '1037'  // Arines
]);

// Best-effort element guesses (game data has none). '?' = uncertain → emits a
// TODO comment in the output for you to verify.
const ELEMENT_GUESSES = {
  '0004': ['water', '?'], // Gray
  '0005': ['wind', '?'], // Rou
  '0006': ['dark', '?'], // Olstein
  '0008': ['fire', '?'], // Rubia
  '0030': ['fire', '?'], // Layla
  '0031': ['light', '?'], // Elpis
  '0032': ['dark', '?'], // Loen
  '0033': ['wind'], // Nebris
  '0034': ['dark'], // Morpeah
  '0035': ['light'], // Sacred Justia
  '0036': ['light', '?'], // Olivier
  '0037': ['dark', '?'], // Blade
  '0038': ['dark'], // Liberta
  '0039': ['dark', '?'], // Sonya
  '0040': ['light', '?'], // Darian
  '0041': ['light', '?'], // Tyr
  '0042': ['dark', '?'], // Palette
  '0200': ['fire'], // Eris
  '0201': ['water'], // Roxy
  '0202': ['water', '?'], // Yomi
  '0203': ['fire', '?'], // Yozakura
  '0204': ['water'], // Yumi
  '0205': ['wind', '?'], // Hikage
  '0206': ['fire', '?'], // Goblin Slayer
  '0207': ['light'], // Priestess
  '0208': ['wind'], // High Elf Archer
  '0209': ['light'], // Sword Maiden
  '0210': ['fire'], // Karuga
  '0603': ['fire', '?'], // Alec
  '0604': ['dark'], // Celia
  '0605': ['fire'], // Anastasia
  '0606': ['water', '?'], // Lecliss
  '0607': ['fire', '?'], // Rafina
  '0608': ['water', '?'], // Elise
  '0611': ['wind', '?'], // Eleaneer
  '0613': ['dark', '?'], // Dalvi
  '0614': ['wind', '?'], // Zenith
  '0620': ['dark', '?'], // Andrew
  '0630': ['fire', '?'], // Ingrid
  '0633': ['water'], // Cynthia
  '0634': ['light'], // Julie
  '0651': ['wind', '?'], // Yuri
  '0658': ['wind', '?'], // Nartas
  '0664': ['light', '?'], // Angelica
  '0668': ['light'], // Refithea
  '0669': ['water'], // Glacia
  '0670': ['wind', '?'], // Ventana
  '0671': ['dark'], // Granhildr
  '0672': ['wind'], // Venaka
  '0673': ['water'], // Levia
  '0674': ['light'], // Michaela
  '0675': ['dark', '?'], // Luvencia
  '0676': ['fire', '?'], // Wilhelmina
  '0677': ['light', '?'], // Granadair
  '0678': ['dark'], // Mamonir
  '1001': ['fire', '?'], // Gynt
  '1002': ['water', '?'], // Fred
  '1003': ['light', '?'], // Lisianne
  '1004': ['wind', '?'], // Remnunt
  '1005': ['fire', '?'], // Wiggle
  '1006': ['dark', '?'], // Lucrezia
  '1008': ['fire', '?'], // Bernie
  '1011': ['dark', '?'], // Seir
  '1012': ['wind', '?'], // Jayden
  '1013': ['fire', '?'], // Emma
  '1014': ['light', '?'], // Samay
  '1015': ['dark', '?'], // Kry
  '1016': ['dark'], // Celia (The Curse)
  '1032': ['fire', '?'], // Carlson
  '1033': ['wind', '?'], // Lydia
  '1034': ['fire', '?'], // Rigenette
  '1035': ['wind', '?'], // Beatrice
  '1036': ['water', '?'] // Maria
};

const FALLBACK_ELEMENTS = ['fire', 'water', 'wind', 'light', 'dark'];

// CharInfo(Dropped).json has minor syntax slips (missing commas) — repair
// before parsing.
let raw = fs.readFileSync(path.join(root, 'CharInfo(Dropped).json'), 'utf8');
raw = raw.replace(/("(?:[^"\\]|\\.)*")(\s*\r?\n\s*")/g, '$1,$2');
const charInfo = JSON.parse(raw);

const invenDir = path.join(root, 'public/brown-dust-2-asset/ui/illust/illust_inven_char');
const skillDir = path.join(root, 'public/brown-dust-2-asset/ui/illust/illust_skill_char');

const stemsIn = (dir, prefix) => {
  const map = {};
  for (const f of fs.readdirSync(dir)) {
    const m = f.match(new RegExp(`^${prefix}_(char(\\d{6})_\\d+)\\.png$`));
    if (m) map[m[2]] = m[1];
  }
  return map;
};
const invenByCostume = stemsIn(invenDir, 'illust_inven');
const skillByCostume = stemsIn(skillDir, 'illust_skill');

const statsForRarity = (r) =>
  r >= 5 || r === 0
    ? { baseAtk: 900 }
    : r === 4
      ? { baseAtk: 820 }
      : { baseAtk: 740 };

const q = JSON.stringify;
const lines = [];

lines.push('// SCAFFOLD PREVIEW — generated by scripts/generate-roster.mjs. Not imported');
lines.push('// by the app. Copy new entries into data/characters.ts (the source of truth)');
lines.push('// and fix elements/stats there.');
lines.push('');
lines.push('import { Character, Costume } from "../types";');
lines.push('import { invenIllust, skillIllust } from "./assets";');
lines.push('');
lines.push('// Placeholder costume: real id/name/art, generic single-target 200% skill.');
lines.push('const basicCostume = (id: string, name: string, stem: string | null): Costume => ({');
lines.push('  id,');
lines.push('  name,');
lines.push('  invenImage: stem ? invenIllust(stem) : undefined,');
lines.push('  image: stem ? skillIllust(stem) : undefined,');
lines.push('  skill: {');
lines.push('    id: `s${id}`,');
lines.push('    name,');
lines.push('    spCost: 2,');
lines.push('    cooldown: 2,');
lines.push('    hitCount: 1,');
lines.push('    scaling: 200,');
lines.push('    damageType: "physical",');
lines.push('    targetShape: "single",');
lines.push('    effects: [],');
lines.push('  },');
lines.push('});');
lines.push('');
lines.push('export const ROSTER_TEMPLATES: Omit<Character, "id">[] = [');

let count = 0;
for (const c of [...charInfo].sort((a, b) => a.charId.localeCompare(b.charId))) {
  if (!c.charName) continue; // placeholder rows (e.g. charId 7040)
  if (HAND_TUNED_CHAR_IDS.has(c.charId)) continue;

  const [element, uncertain] = ELEMENT_GUESSES[c.charId] ?? [
    FALLBACK_ELEMENTS[(parseInt(c.charId, 10) || 0) % 5],
    '?'
  ];
  const rarity = c.rarity ?? 0;
  const { baseAtk } = statsForRarity(rarity);

  const costumes = (c.costumes || []).map((co) => ({
    id: co.costumeId,
    name: co.costumeName || co.costumeId,
    stem: invenByCostume[co.costumeId] ?? skillByCostume[co.costumeId] ?? null
  }));
  const base = costumes.find((co) => co.stem);

  lines.push(`  // ── ${c.charName.toUpperCase()} (${c.charId} · r${rarity}) ──`);
  lines.push('  {');
  lines.push(`    charId: ${q(c.charId)},`);
  lines.push(`    name: ${q(c.charName)},`);
  lines.push(`    element: ${q(element)},${uncertain ? ' // TODO: verify element' : ''}`);
  lines.push(`    rarity: ${rarity},`);
  lines.push(`    baseAtk: ${baseAtk},`);
  lines.push('    baseMatk: 0,');
  lines.push('    baseCritRate: 10,');
  lines.push('    baseCritDmg: 50,');
  lines.push('    baseDef: 10,');
  lines.push('    baseMres: 10,');
  lines.push('    basePropDmg: 0,');
  lines.push('    level: 100,');
  lines.push('    upgradeLevel: 5,');
  if (base) lines.push(`    image: invenIllust(${q(base.stem)}),`);
  lines.push('    costumes: [');
  for (const co of costumes) {
    lines.push(`      basicCostume(${q(co.id)}, ${q(co.name)}, ${q(co.stem)}),`);
  }
  lines.push('    ],');
  lines.push('  },');
  count++;
}

lines.push('];');
lines.push('');

fs.writeFileSync(path.join(root, 'scripts/roster-scaffold.preview.ts'), lines.join('\n'));
console.log(
  `Wrote scripts/roster-scaffold.preview.ts with ${count} characters (hand-tuned ones excluded).`
);
console.log('Copy any NEW entries into data/characters.ts by hand — roster.ts is the source of truth.');
